# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetPlayerPersonalShowReq.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eGetPlayerPersonalShowReq.proto\x12\x0bGameService\"R\n\x1cGetPlayerPersonalShowRequest\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x04\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetPlayerPersonalShowReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETPLAYERPERSONALSHOWREQUEST']._serialized_start=47
  _globals['_GETPLAYERPERSONALSHOWREQUEST']._serialized_end=129
# @@protoc_insertion_point(module_scope)
