# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequestAddingFriendreq.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cRequestAddingFriendreq.proto\x12\x0bGameService\"T\n\x1bRequestAddingFriendrequests\x12\x12\n\naccount_id\x18\x01 \x01(\x03\x12\x13\n\x0brequests_id\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RequestAddingFriendreq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTADDINGFRIENDREQUESTS']._serialized_start=45
  _globals['_REQUESTADDINGFRIENDREQUESTS']._serialized_end=129
# @@protoc_insertion_point(module_scope)
